automated mm ratings and skill verification
topcoder-platform/member-profile-processor pull request #1
Opened 2022-12-12 10:18 UTC by bountyC0d3r

2022-12-12 14:45 UTC, rakibansary commented on package.json
> +    "node": "10.x"
We should use the latest LTS

2022-12-13 05:06 UTC, bountyC0d3r commented
using the latest LTS would be a problem, as somehow `ifxnjs` is giving
compilation error


On Mon, 12 Dec 2022 at 20:16, Rakib Ansary Saikot ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In package.json
> <https://github.com/topcoder-platform/member-profile-processor/pull/1#discussion_r1045918678>
> :
>
> > +    "config": "^3.3.8",
> +    "get-parameter-names": "^0.3.0",
> +    "ifxnjs": "^10.0.5",
> +    "joi": "^17.7.0",
> +    "lodash": "^4.17.21",
> +    "no-kafka": "^3.4.3",
> +    "q": "^1.5.1",
> +    "superagent": "^8.0.3",
> +    "superagent-prefix": "0.0.2",
> +    "tc-core-library-js": "appirio-tech/tc-core-library-js.git#v2.6.4",
> +    "topcoder-healthcheck-dropin": "^1.0.3",
> +    "winston": "^3.8.2",
> +    "xml2js": "^0.4.23"
> +  },
> +  "engines": {
> +    "node": "10.x"
>
> We should use the latest LTS
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/topcoder-platform/member-profile-processor/pull/1#pullrequestreview-1213717948>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOGQUI6ZWA33QAUYHPVPO3WM43C3ANCNFSM6AAAAAAS3XZRTI>
> .
> You are receiving this because you authored the thread.Message ID:
> <topcoder-platform/member-profile-processor/pull/1/review/1213717948@
> github.com>
>

2023-01-02 06:19 UTC, rakibansary requested changes

2023-01-02 06:19 UTC, rakibansary commented on src/common/helper.js
> + * @returns {array} submissions
Let's update @returns {array} submissions to `@return {Promise<array>}` - causes issues with linters reporting consumers of this method as using "unnecessary await"

2023-01-02 06:19 UTC, rakibansary commented on src/common/helper.js
> + * @returns {Object} superagent instance configured with Authorization header and API url prefix
@returns {Promise<Object>}

2023-01-02 06:19 UTC, rakibansary commented on src/common/informixDB.js
> + * @return {Object} Informix connection
@returns {Promise<Object>}

2023-01-02 06:19 UTC, rakibansary commented on src/common/informixDB.js
> + * @returns {array} rows from long_comp_result table
@returns {Promise<array>}

2023-01-02 06:19 UTC, rakibansary commented on src/common/helper.js
> + * @returns {array} submissions
![image](https://user-images.githubusercontent.com/1445965/210199865-eebb88b8-0d22-4e6a-a66b-40d88137ea1d.png)

2023-01-02 06:48 UTC, rakibansary approved these changes

2023-01-02 06:49 UTC, merged